const allSkills = {
    skills: [
      { id: 1, name: "JavaScript" },
      { id: 2, name: "Python" },
      { id: 3, name: "Java" },
      { id: 4, name: "C++" },
      { id: 5, name: "React" },
      { id: 6, name: "Node.js" },
      { id: 7, name: "SQL" },
      { id: 8, name: "AWS" },
      { id: 9, name: "Docker" },
      { id: 10, name: "Machine Learning" },
      { id: 11, name: "Cybersecurity" },
      { id: 12, name: "DevOps" },
      { id: 13, name: "Data Analysis" },
      { id: 14, name: "Data Science" },
      { id: 15, name: "Blockchain" },
      { id: 16, name: "Cloud Computing" },
      { id: 17, name: "Internet of Things (IoT)" },
      { id: 18, name: "Mobile Development" },
      { id: 19, name: "Swift" },
      { id: 20, name: "Flutter" },
      { id: 21, name: "Kotlin" },
      { id: 22, name: "Ruby" },
      { id: 23, name: "PHP" },
      { id: 24, name: "Go" },
      { id: 25, name: "TypeScript" },
      { id: 26, name: "HTML" },
      { id: 27, name: "CSS" },
      { id: 28, name: "Vue.js" },
      { id: 29, name: "Angular" },
      { id: 30, name: "Sass" },
      { id: 31, name: "GraphQL" },
      { id: 32, name: "API Development" },
      { id: 33, name: "Artificial Intelligence (AI)" },
      { id: 34, name: "Natural Language Processing (NLP)" },
      { id: 35, name: "TensorFlow" },
      { id: 36, name: "PyTorch" },
      { id: 37, name: "Big Data" },
      { id: 38, name: "SQL Server" },
      { id: 39, name: "MongoDB" },
      { id: 40, name: "Redis" },
      { id: 41, name: "PostgreSQL" },
      { id: 42, name: "AWS Lambda" },
      { id: 43, name: "Serverless Architecture" },
      { id: 44, name: "Virtualization" },
      { id: 45, name: "Kubernetes" },
      { id: 46, name: "Jenkins" },
      { id: 47, name: "CI/CD" },
      { id: 48, name: "Agile Methodology" },
      { id: 49, name: "Scrum" },
      { id: 50, name: "Test-Driven Development (TDD)" },
      { id: 51, name: "Git" },
      { id: 52, name: "GitHub" },
      { id: 53, name: "Version Control" },
      { id: 54, name: "Communication" },
      { id: 55, name: "Teamwork" },
      { id: 56, name: "Problem-Solving" },
      { id: 57, name: "Time Management" },
      { id: 58, name: "Adaptability" },
      { id: 59, name: "Emotional Intelligence" },
      { id: 60, name: "Leadership" },
      { id: 61, name: "Conflict Resolution" },
      { id: 62, name: "Creativity" },
      { id: 63, name: "Public Speaking" },
      { id: 64, name: "Writing" },
      { id: 65, name: "Negotiation" },
      { id: 66, name: "Decision Making" },
      { id: 67, name: "Critical Thinking" },
      { id: 68, name: "Collaboration" },
      { id: 69, name: "Customer Service" },
      { id: 70, name: "Sales" },
      { id: 71, name: "Project Management" },
      { id: 72, name: "Event Planning" },
      { id: 73, name: "Presentation Skills" },
      { id: 74, name: "Business Strategy" },
      { id: 75, name: "Branding" },
      { id: 76, name: "Market Research" },
      { id: 77, name: "Graphic Design" },
      { id: 78, name: "UI/UX Design" },
      { id: 79, name: "Logo Design" },
      { id: 80, name: "Web Design" },
      { id: 81, name: "Wireframing" },
      { id: 82, name: "Prototyping" },
      { id: 83, name: "User Research" },
      { id: 84, name: "Photography" },
      { id: 85, name: "Video Editing" },
      { id: 86, name: "Animation" },
      { id: 87, name: "Film Production" },
      { id: 88, name: "Sound Design" },
      { id: 89, name: "Art Direction" },
      { id: 90, name: "Public Relations" },
      { id: 91, name: "Content Writing" },
      { id: 92, name: "Copywriting" },
      { id: 93, name: "Social Media Marketing" },
      { id: 94, name: "Content Marketing" },
      { id: 95, name: "SEO" },
      { id: 96, name: "SEM" },
      { id: 97, name: "Email Marketing" },
      { id: 98, name: "Video Marketing" },
      { id: 99, name: "Affiliate Marketing" },
      { id: 100, name: "Growth Hacking" },
      { id: 101, name: "E-commerce" },
      { id: 102, name: "App Store Optimization (ASO)" },
      { id: 103, name: "Advertising" },
      { id: 104, name: "Brand Management" },
      { id: 105, name: "Digital Marketing" },
      { id: 106, name: "Community Management" },
      { id: 107, name: "User Acquisition" },
      { id: 108, name: "Influencer Marketing" },
      { id: 109, name: "CRM Tools (Salesforce, HubSpot)" },
      { id: 110, name: "Customer Relationship Management (CRM)" },
      { id: 111, name: "Data Entry" },
      { id: 112, name: "Web Analytics (Google Analytics, Mixpanel)" },
      { id: 113, name: "Business Intelligence (BI)" },
      { id: 114, name: "ERP Software" },
      { id: 115, name: "Microsoft Office Suite" },
      { id: 116, name: "Excel (Advanced)" },
      { id: 117, name: "Microsoft Word" },
      { id: 118, name: "PowerPoint" },
      { id: 119, name: "Data Visualization (Tableau, Power BI)" },
      { id: 120, name: "Financial Modeling" },
      { id: 121, name: "Investment Analysis" },
      { id: 122, name: "Accounting" },
      { id: 123, name: "Taxation" },
      { id: 124, name: "Legal Research" },
      { id: 125, name: "Compliance" },
      { id: 126, name: "Patent Law" },
      { id: 127, name: "Real Estate" },
      { id: 128, name: "Fundraising" },
      { id: 129, name: "Crowdfunding" },
      { id: 130, name: "Startup Mentorship" },
      { id: 131, name: "Venture Capital" },
      { id: 132, name: "Angel Investing" },
      { id: 133, name: "Public Speaking" },
      { id: 134, name: "Coaching" },
      { id: 135, name: "Mentoring" },
      { id: 136, name: "Consulting" },
      { id: 137, name: "Personal Branding" },
      { id: 138, name: "Time Management" },
      { id: 139, name: "Stress Management" },
      { id: 140, name: "Mindfulness" },
      { id: 141, name: "Leadership Development" },
      { id: 142, name: "Entrepreneurship" },
      { id: 143, name: "Corporate Strategy" },
      { id: 144, name: "Executive Leadership" },
      { id: 145, name: "Risk Management" },
      { id: 146, name: "Change Management" },
      { id: 147, name: "Business Development" },
      { id: 148, name: "Innovation Management" },
      { id: 149, name: "Negotiation Skills" },
      { id: 150, name: "Crisis Management" },
      { id: 151, name: "Employee Engagement" },
      { id: 152, name: "Employee Training" },
      { id: 153, name: "Workplace Diversity" },
      { id: 154, name: "Human Resources (HR)" },
      { id: 155, name: "Recruitment" },
      { id: 156, name: "Onboarding" },
      { id: 157, name: "Payroll" },
      { id: 158, name: "Employee Relations" },
      { id: 159, name: "Labor Law" },
      { id: 160, name: "Workplace Safety" },
      { id: 161, name: "Ethics" },
      { id: 162, name: "Operations Management" },
      { id: 163, name: "Logistics" },
      { id: 164, name: "Supply Chain Management" },
      { id: 165, name: "Manufacturing" },
      { id: 166, name: "Lean Six Sigma" },
      { id: 167, name: "Agile Project Management" },
      { id: 168, name: "Scrum Master" },
      { id: 169, name: "Quality Assurance (QA)" },
      { id: 170, name: "Product Management" },
      { id: 171, name: "Product Design" },
      { id: 172, name: "Prototyping" },
      { id: 173, name: "User Testing" },
      { id: 174, name: "Creative Direction" },
      { id: 175, name: "Branding and Positioning" },
      { id: 176, name: "Brand Strategy" },
      { id: 177, name: "Global Marketing" },
      { id: 178, name: "Cultural Awareness" },
      { id: 179, name: "International Business" },
      { id: 180, name: "Global Trade" },
      { id: 181, name: "Cross-Cultural Communication" },
      { id: 182, name: "International Marketing" },
      { id: 183, name: "Global Branding" },
      { id: 184, name: "Market Access" },
      { id: 185, name: "International Sales" },
      { id: 186, name: "Global Strategy" },
      { id: 187, name: "Global Logistics" },
      { id: 188, name: "E-commerce Strategy" },
      { id: 189, name: "Cross-Border Payment Systems" },
      { id: 190, name: "Global Supply Chain" },
      { id: 191, name: "Cultural Diplomacy" },
      { id: 192, name: "Security Studies" },
      { id: 193, name: "Peace Studies" },
      { id: 194, name: "Global Governance" },
      { id: 195, name: "Public Administration" },
      { id: 196, name: "Municipal Governance" },
      { id: 197, name: "City Planning" },
      { id: 198, name: "Disaster Management" },
      { id: 199, name: "Sustainability Studies" },
      { id: 200, name: "Environmental Policy" }
    ]
  };
  